### PR TITLE
LCH-6061: Fix deprecations for symfony 3.4.

### PR DESCRIPTION
**Pull request by amangrover90**

### CODE REVIEW

**Review by saxumVermes — CHANGES_REQUESTED** [review]
I think here as well, we can revise the dispatch() arguments. From Symfony 5 ordering changes, better get ahead of that deprecation.

**Comment by saxumVermes** [comment]
Also all the symfony 3.4 from composer.json needs to be removed.

**Comment by amangrover90** [comment]
> 

Yeah I missed that, was gonna do it after lunch.

**Review by narendradesai — APPROVED** [review]
LGTM 👍🏻

**Review by saxumVermes — APPROVED** [review]
Looks good! Let's roll it!

**Pull request merged**
