### PR TITLE
LAT-460 | On unrecognized entity schema, content-hub-php module should fall back to guessing the current localized schema, instead of throwing off DataAdapterException.

### PR DESCRIPTION
**Pull request by ynx**

### CODE REVIEW

**Comment by matthewmorley** [comment]
This fixed the initial test failures with D7. Running prior passing D7 tests, but not expecting any new failures.

**Comment by ynx** [comment]
Thank you @matthewmorley. If you are okay with the code, we can merge in any time now. Can I please assign the ticket's review (therefore merge) to you?

**Comment by matthewmorley** [comment]
Assigned myself as reviewer, I'll merge it in shortly. We also need to cut a new version and require it from d7, I'm less clear on that. But we can sync up monday.

**Comment by matthewmorley** [comment]
Tests passed. Will merge later tonight.

**Comment by ynx** [comment]
Awesome. Thank you @matthewmorley!

**Pull request merged**
